# Generated by Django 2.2.3 on 2019-12-16 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publsihed_date',
            new_name='published_date',
        ),
    ]
